### ISSUE TITLE
Resume point left behind when using with upnext addon

### ISSUE THREAD

**Issue by Dnkhatri** [bossanova808/script.service.playbackresumer#1]
When I am using this addon  with upnext addon after watching a few episodes I find all the watched episodes have resume point left behind 1-2~min in to each video.

**Comment by bossanova808** [comment]
Ok - I have never used the Next Up addon.  Not really sure why it would interfere with the marking of the resumed position.

A few questions - when you say resume point left in video - do you mean after fully watching an episode, there is a resume point on to two minutes in from the start?  Or from the end?  

Also - you are using Kodi Matrix right?  I am only the maintainer for the Matrix version on and won't be fixing the older versions.

In any case, please post a FULL debug log of all this happening to pastebin or similar so I can have a look what is going on.

**Comment by Dnkhatri** [comment]
Yeah using matrix the video is marked watched but a resume point is left behind. The resume point is at the start of the video. I will post the debug log later any specific components you want me to log or just the normal debug log?

**Comment by bossanova808** [comment]
Normal debug log should fine be I think.

I presume Next Up is taking over moving to the next file, so not sure there will be an easy fix to clear the resume point.  Basically this addon just monitors for playing files and periodically updates the resume point in the background...TBH I think it's really Kodi's job to clear the resume when it marks it as watched (or Next Up, if that is doing that).  

But happy to look at it to see if I can do something...

**Comment by Dnkhatri** [comment]
> Normal debug log should fine be I think.
> 
> I presume Next Up is taking over moving to the next file, so not sure there will be an easy fix to clear the resume point. Basically this addon just monitors for playing files and periodically updates the resume point in the background...TBH I think it's really Kodi's job to clear the resume when it marks it as watched (or Next Up, if that is doing that).
> 
> But happy to look at it to see if I can do something...

Thanks once you point me in the right direction I can post this bug in kodi or upnext. I personally feel it has something to do with upnext as if I recall correctly one of the upnext dev mentioned that the 2nd video is loaded before the 1st ends to make the playback seamless.

**Comment by bossanova808** [comment]
No worries, just post the log when you can.

**Comment by bossanova808** [comment]
Ok, going to close this as an issue until such a time as logs are provided if that is necessary....assuming it is/was a bug with upnext.

**Comment by Dnkhatri** [comment]
> Ok, going to close this as an issue until such a time as logs are provided if that is necessary....assuming it is/was a bug with upnext.

Sorry I have been busy plus with the kodi 19 nightlies looks like a lot work is being done around addons so I will wait tell its more stable to see if I still have this problem.
