### ISSUE TITLE
where to get the python2 version?

### ISSUE THREAD

**Issue by mo-han** [bossanova808/script.service.playbackresumer#2]
the hevc HW accel of my tvbox cannot work well in kodi 18 and 19, it has to stay with kodi 17.
is there any way to get the old version working with kodi 17 / python 2?

**Comment by bossanova808** [comment]
Python 2 code was available in the original forum thread... That's what I grabbed when I took it over. 

I have it still installed on my K18 system here so if you can't find it I can zip it up for you I guess.

**Comment by bossanova808** [comment]
Here you go:

[script.service.playbackresumer-python2.zip](https://github.com/bossanova808/script.service.playbackresumer/files/5214006/script.service.playbackresumer-python2.zip)

**Comment by mo-han** [comment]
thx
just managed to install from the mirror on bitbucket, i suppose it's identical with yours.
anyway, also upload my zip:
[digiltd-script.service.playbackresumer-47cdae6245c4.zip](https://github.com/bossanova808/script.service.playbackresumer/files/5214080/digiltd-script.service.playbackresumer-47cdae6245c4.zip)
