### ISSUE TITLE
TypeError thrown

### ISSUE THREAD

**Issue by dolorosus** [bossanova808/script.service.playbackresumer#3]
`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--`
`   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!`
`  Error Type: <class 'TypeError'>`
`  Error Contents: '<' not supported between instances of 'NoneType' and 'int'`
`  Traceback (most recent call last):`
`    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.playbackresumer/resources/lib/player.py", line 32, in onPlayBackStopped`
`      self.update_resume_point(-2)`
`    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.playbackresumer/resources/lib/player.py", line 134, in update_resume_point`
`      if Store.library_id < 0:`
`  TypeError: '<' not supported between instances of 'NoneType' and 'int'`
`  -->End of Python script error report<--`

**Comment by bossanova808** [comment]
Please re-submit your issues with a **complete** debug log and description of what you were doing / what went wrong
