### ISSUE TITLE
unhandled exception  'Type Error' after pressing 'pause/playback/pause' and after pressing 'stop'

### ISSUE THREAD

**Issue by dolorosus** [bossanova808/script.service.playbackresumer#4]
Full debug log:
https://paste.kodi.tv/fogezilucu.kodi

Steps to reproduce:
 start video, press 'pause', press 'play'
 and also after pressing 'stop'

**Comment by bossanova808** [comment]
I'll have a look - what sort of file are you playing, as it appears not to be properly in your library:

```
2021-08-22 11:51:48.233 T:1972    DEBUG <general>: ### Kodi Playback Resumer 2.0.2 - JSON-RPC Files.GetFileDetails response: {"id": "fileDetailsCheck", "jsonrpc": "2.0", "result": {"filedetails": {"label": "tagesschau, 1000 Uhr ARD Mediathek.mp4", "type": "unknown"}}}
2021-08-22 11:51:48.234 T:1972    DEBUG <general>: ### Kodi Playback Resumer 2.0.2 - Unsupported type of video unknown for /storage/5885-1605/Android/data/org.primftpd/files/tagesschau, 1000 Uhr ARD Mediathek.mp4
```

But it should still cope, of course.

**Comment by bossanova808** [comment]
Could change line 134 of player.py to:

```
if not Store.library_id or Store.library_id < 0:
```

And repeat your test, it should solve your issue.

**Comment by dolorosus** [comment]
That's right. It's not mandatory having a file n the lib for playing it.

I would suggest to use a try catch block, for handling this specific error without to much hassle:

        # Now, update the Kodi library resume point for this video via JSON-RPC API
        try:
            if Store.library_id < 0:
                log(f'Can\'t update Kodi native resume point because {Store.currently_playing_file_path} is not in the library')
                return
        except (TypeError):
            pass

**Comment by bossanova808** [comment]
(Well, yes, obviously re: files not in library).

But I was wanting you to check that line, just to be sure.  In any case, I'll add the fix soon.
