### ISSUE TITLE
Possible audio player addition

### ISSUE THREAD

**Issue by ainuke** [bossanova808/script.service.playbackresumer#6]
Would be great if this could work for the audio player as well as the video. 

My use case is with a raspberry Pi for media playing in the car. I have a Mausberry 4A power supply that monitors the acc line and gives the pi about 30-40 seconds to shut down gracefully before killing the power. On resume, though, Kodi wants to start over with music selection, which is a bummer if you just ran got out of the car for a minute. 

In a perfect world, Kodi would remember where in the file structure the player was, in addition to where in the song, and cue the song at the same point. I’d say having it cued in a paused state would be ideal, so that it could be resumed when ready, not just automatically blasting everyone without notice. If I had a wishlist these things would be on it. 

Thanks for the consideration!
Erik

**Comment by gargamon2** [comment]
Hello,
I too would like to see resume work for music playlists. There are a couple of old addona that used to contain this capability but they were written in  python 2 so no longer work. 

Here's the links to the old python addons. 
https://github.com/drax68/kodi-resume
https://github.com/idorel77/kodi-resume
It looks like they are both forks from the same branch.

I'll add this text to the forum thread too.

**Comment by bossanova808** [comment]
Closing, as not an issue but a feature request.  See forum.
