### ISSUE TITLE
I can't figure out how to install the addon

### ISSUE THREAD

**Issue by oathzed** [bossanova808/script.service.playbackresumer#8]
Hello,

I'd really like to try your addon but I can't figure out how to get it installed. I've downloaded the zip and put it on my downloads folder on Android tv. But when I navigate in Kodi "install from zip file" it is there but the ok button is greyed out.. I'm so confused lol.

Please help 

Thank you!

**Comment by oathzed** [comment]
Nvm it was a permission setting, got it sorted. thanks!

**Comment by bossanova808** [comment]
You know you can just install it via the Kodi main repo though, right?  There's no need for a manual zip install...I mean, I guess you can, but not sure why you would...
